version: '2'
services:
  panel-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/panel/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=panel
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
